# -*- coding: utf-8 -*-
"""Vinothini_stage1_2_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6xXwiBbRyUGajWdEPciTbuHQur8dAFo
"""

#Stage 1: Basic Calculator
def calculator(num1,num2,operator):
  result=0
  if operator == "+":
    result = num1 + num2

  elif operator == "/":
    if num2 ==0:
      print(f"num2 is not allowed the zero. division by zero")
    else:
      result = num1 / num2
     # print("Result =" result)

  elif operator == "-":
    result = num1 - num2
   # print("Result =" result)

  elif operator == "*":
    result = num1 * num2
   # print("Result =" result)

  else:
    print(f"opperator error")

  return result

#Stage 2: Add Result Check

def check_number(num1,num2,operator):
  result =calculator(num1,num2,operator)
  if result > 0:
    check="Positive"
  elif result < 0:
    check="Negative"
  else:
    check="Zero"
  return  result,check

num1=int(input("Enter first number: "))
num2=int(input("Enter second number: "))
operator=input("Enter operator: ")
result_num, check_num=check_number(num1,num2,operator)
print(f"Result = {result_num}\n{check_num}")

"""Stage 3: Student Grade Calculator
Task: Calculate student grade based on marks in 3 subjects.

Input: Student name, 3 subject marks (0-100)

Calculate:

Total marks
Percentage = (total/300) * 100
Grade Logic:

A: >= 75%
B: >= 60%
C: >= 40%
F: < 40%
Output: Name, Total, Percentage, Grade


"""

def grade_calculator(sub1,sub2,sub3):
  total=sub1+sub2+sub3
  percentage=(total/300)*100
  if percentage >= 75:
    grade="A"
  elif percentage >=60:
    grade="B"
  elif percentage >=40:
    grade="C"
  else:
    grade="F"

  return total,percentage,grade

name=input(f"Enter the name: ")
sub1=int(input(f"Enter the marks of sub1: "))
sub2=int(input(f"Enter the marks of sub2: "))
sub3=int(input(f"Enter the marks of sub3: "))
total_mark,percentage,grade=grade_calculator(sub1,sub2,sub3)
print(f"Name: {name}\nTotal: {total_mark}\nPercentage: {percentage}\nGrade: {grade}")